[package]
name = "shader"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = [ "dylib"]

[dependencies]
spirv-std = { version = "0.9" }
glam = { version = "0.29", default-features = false, features = ["libm"] }
bytemuck = { version = "1.19", features = ["derive"] }